version: '3.8'

services:
    app:
        build:
            context: ./docker/app
            target: production
            args:
                - WWWGROUP=${WWWGROUP:-1000}
                - WWWUSER=${WWWUSER:-1000}
        ports:
            - '${APP_PORT:-9000}:9000'
        restart: unless-stopped
        command: '/usr/bin/supervisord -n'
        tty: true
        volumes:
            - ./:/var/www/html
        networks:
            - backend

    redis:
        image: redis:7.2.1-alpine3.18
        restart: unless-stopped
        volumes:
            - storage-redis:/data
        networks:
            - backend

networks:
    backend:
        driver: bridge

volumes:
    storage-redis:
